// 금감원 API 키 발급 전까지 사용하는 mock 데이터
// API 키 발급 후 getProducts(), chatBot(), personalityTest() 에서 실제 API 호출로 교체

const MOCK_DEPOSIT_PRODUCTS = [
  {
    fin_prdt_cd: "WR0001B",
    kor_co_nm: "국민은행",
    fin_prdt_nm: "KB Star 정기예금",
    join_way: "인터넷,스마트폰",
    mtrt_int: "만기 후 1개월 이내: 약정이율의 50%",
    spcl_cnd: "급여이체 또는 카드실적 보유 시 우대금리 0.2%p",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: "1인 1계좌",
    max_limit: null,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", intr_rate: 3.5, intr_rate2: 3.7 },
      { save_trm: "12", intr_rate_type_nm: "단리", intr_rate: 3.8, intr_rate2: 4.0 },
      { save_trm: "24", intr_rate_type_nm: "단리", intr_rate: 3.6, intr_rate2: 3.8 },
      { save_trm: "36", intr_rate_type_nm: "단리", intr_rate: 3.5, intr_rate2: 3.7 },
    ],
  },
  {
    fin_prdt_cd: "WR0002B",
    kor_co_nm: "신한은행",
    fin_prdt_nm: "신한 쏠편한 정기예금",
    join_way: "인터넷,스마트폰,전화(텔레뱅킹)",
    mtrt_int: "만기 후 1개월 이내: 약정이율의 50%",
    spcl_cnd: "신한카드 월 30만원 이상 사용 시 0.1%p 우대",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: null,
    max_limit: 100000000,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", intr_rate: 3.4, intr_rate2: 3.5 },
      { save_trm: "12", intr_rate_type_nm: "단리", intr_rate: 3.9, intr_rate2: 4.1 },
      { save_trm: "24", intr_rate_type_nm: "단리", intr_rate: 3.7, intr_rate2: 3.9 },
    ],
  },
  {
    fin_prdt_cd: "WR0003B",
    kor_co_nm: "하나은행",
    fin_prdt_nm: "하나 정기예금",
    join_way: "영업점,인터넷,스마트폰",
    mtrt_int: "만기 후: 보통예금 금리 적용",
    spcl_cnd: "하나멤버스 포인트 보유 시 0.1%p 우대",
    join_deny: "1",
    join_member: "실명의 개인 및 법인",
    etc_note: null,
    max_limit: null,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", intr_rate: 3.3, intr_rate2: 3.4 },
      { save_trm: "12", intr_rate_type_nm: "단리", intr_rate: 4.0, intr_rate2: 4.2 },
      { save_trm: "36", intr_rate_type_nm: "단리", intr_rate: 3.8, intr_rate2: 4.0 },
    ],
  },
  {
    fin_prdt_cd: "WR0004B",
    kor_co_nm: "우리은행",
    fin_prdt_nm: "WON 플러스 예금",
    join_way: "인터넷,스마트폰",
    mtrt_int: "만기 후 1개월 이내: 약정이율의 50%",
    spcl_cnd: "우리카드 실적 보유 시 0.2%p 우대",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: null,
    max_limit: 200000000,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", intr_rate: 3.6, intr_rate2: 3.8 },
      { save_trm: "12", intr_rate_type_nm: "단리", intr_rate: 4.1, intr_rate2: 4.3 },
      { save_trm: "24", intr_rate_type_nm: "단리", intr_rate: 3.9, intr_rate2: 4.1 },
    ],
  },
  {
    fin_prdt_cd: "WR0005B",
    kor_co_nm: "농협은행",
    fin_prdt_nm: "NH왈츠회전예금II",
    join_way: "영업점,인터넷,스마트폰",
    mtrt_int: "만기 후: 일반 보통예금 금리",
    spcl_cnd: "없음",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: "회전식 금리 적용",
    max_limit: null,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "12", intr_rate_type_nm: "단리", intr_rate: 3.7, intr_rate2: 3.7 },
      { save_trm: "24", intr_rate_type_nm: "단리", intr_rate: 3.8, intr_rate2: 3.8 },
    ],
  },
];

const MOCK_SAVING_PRODUCTS = [
  {
    fin_prdt_cd: "WR0001S",
    kor_co_nm: "국민은행",
    fin_prdt_nm: "KB 내맘대로 적금",
    join_way: "인터넷,스마트폰",
    mtrt_int: "만기 후 1개월 이내: 약정이율의 50%",
    spcl_cnd: "급여이체 실적 보유 시 0.3%p 우대",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: "자유적립식",
    max_limit: null,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", rsrv_type_nm: "자유적립식", intr_rate: 4.0, intr_rate2: 4.3 },
      { save_trm: "12", intr_rate_type_nm: "단리", rsrv_type_nm: "자유적립식", intr_rate: 4.5, intr_rate2: 4.8 },
    ],
  },
  {
    fin_prdt_cd: "WR0002S",
    kor_co_nm: "신한은행",
    fin_prdt_nm: "신한 적금",
    join_way: "인터넷,스마트폰,영업점",
    mtrt_int: "만기 후: 보통예금 금리 적용",
    spcl_cnd: "신한카드 월 20만원 이상 사용 시 0.2%p 우대",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: null,
    max_limit: null,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "12", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 4.3, intr_rate2: 4.5 },
      { save_trm: "24", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 4.1, intr_rate2: 4.3 },
      { save_trm: "36", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 4.0, intr_rate2: 4.2 },
    ],
  },
  {
    fin_prdt_cd: "WR0003S",
    kor_co_nm: "하나은행",
    fin_prdt_nm: "하나 청년 적금",
    join_way: "인터넷,스마트폰",
    mtrt_int: "만기 후: 보통예금 금리 적용",
    spcl_cnd: "만 19~34세 가입 시 0.5%p 우대",
    join_deny: "1",
    join_member: "만 19세~34세 실명의 개인",
    etc_note: "청년 전용 상품",
    max_limit: 30000000,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "12", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 5.0, intr_rate2: 5.5 },
      { save_trm: "24", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 4.8, intr_rate2: 5.3 },
    ],
  },
  {
    fin_prdt_cd: "WR0004S",
    kor_co_nm: "우리은행",
    fin_prdt_nm: "우리 SUPER 주거래 적금",
    join_way: "영업점,인터넷,스마트폰",
    mtrt_int: "만기 후 1개월 이내: 약정이율의 50%",
    spcl_cnd: "우리은행 급여이체 + 카드실적 보유 시 최대 1.0%p 우대",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: null,
    max_limit: null,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", rsrv_type_nm: "자유적립식", intr_rate: 3.8, intr_rate2: 4.8 },
      { save_trm: "12", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 4.2, intr_rate2: 5.2 },
    ],
  },
  {
    fin_prdt_cd: "WR0005S",
    kor_co_nm: "농협은행",
    fin_prdt_nm: "NH 올원e적금",
    join_way: "스마트폰",
    mtrt_int: "만기 후: 보통예금 금리 적용",
    spcl_cnd: "NH올원뱅크 앱 가입 시 0.3%p 우대",
    join_deny: "1",
    join_member: "실명의 개인",
    etc_note: "모바일 전용",
    max_limit: 20000000,
    dcls_strt_day: "20240101",
    dcls_end_day: null,
    fin_co_subm_day: "20240101",
    options: [
      { save_trm: "6", intr_rate_type_nm: "단리", rsrv_type_nm: "자유적립식", intr_rate: 4.1, intr_rate2: 4.4 },
      { save_trm: "12", intr_rate_type_nm: "단리", rsrv_type_nm: "정액적립식", intr_rate: 4.6, intr_rate2: 4.9 },
    ],
  },
];

module.exports = { MOCK_DEPOSIT_PRODUCTS, MOCK_SAVING_PRODUCTS };
